### ISSUE TITLE
'serenity client' threads panics at disaptcher

### ISSUE THREAD

**Issue by UninterestinAcc** [zeyla/serenity#205] opened 2017-10-24 03:33 UTC
* [The full backtrace is here](https://gist.github.com/UninterestinAcc/f7db20c43a96c3c49ad1d1d7fb1b155d)
* [Last place the code was at before it went into full panic.](https://github.com/zeyla/serenity/blob/v0.4.1/src/client/dispatch.rs#L59)

I don't have any idea what caused this, but I am submitting this backtrace anyway. ¯\\_(ツ)_/¯

**Comment by teamplz** [comment] 2017-10-26 05:04
I have my bot running on a server in release mode and it doesn't want to join voice after being reconnected. I feel like it's related to this and a thread is being poisoned randomly but I have to confirm it.

Does running in release mode hide this error? I don't know.

**Comment by UninterestinAcc** [comment] 2017-10-27 01:19
Oh god I just realized I can't spell.

Anyway, after this issue happens, the bot is usually unresponsive to text messages as well, manually restarting it fixes it.

**Comment by zeyla** [comment] 2017-10-27 01:22
This erroneous behaviour is fixed in the v0.5.0 branch as a side-effect of something unrelated, but I'd still like to fix the root cause of a panic. Do you have any indicator yet as to what causes this?

**Comment by UninterestinAcc** [comment] 2017-10-27 01:38
Sorry, nope...

**Comment by zeyla** [comment] 2017-11-04 22:45
Closing as this is fixed in v0.5.0, please let us know if this happens again and we can re-open.

**Closed by zeyla** 2017-11-04 22:45 UTC
Labels: bug
